### ISSUE TITLE
How. to get vault. placeholder values

### ISSUE THREAD

**Issue by pradeepkusingh** [Piszmog/cloudconfigclient#20]
### Issue Description
I have configured a vault. with spring. config servers and using vault. values placeholder, but when I use this repo and. fetch the properties from github, still it shows placeholder. not actual valu.

Key : test.password      value: ${vault..secret}

### Steps to Reproduce
Read values. from vault/git placeholders.

### Expected Behavior
We should see actual values from vault placeholder.

**Comment by Piszmog** [comment]
This is expected behavior for this library. My library is not trying to copy or keep parity with Spring magic.

---

If you come from a Java/Spring background, you will notice that this type of magic works - the replacement works out great. This is because Spring is doing a lot of magic for you - checking the vault and doing the replacement for you.

If you use Credhub, it's very similar in behavior where,

Credhub you have the following JSON configuration,
```json
{
  "secret": "my-secret-value"
}
```

Then in your config file that the Config Server pulls (e.g. `application.yml`) you have the following,

```json
secret-value: ${credhub.secret}
```

Using Spring, this all works out great. The injected value of `secret-value` matches the value in Credhub (`my-secret-value`). In order to do this replacement, Spring is doing a lot of work. It needs to know that your application is bounded to a Credhub instance and needs to be able to check the values in it.

Unfortunately, this is not the use case of this library. This library is built primarily to interact with the Config Server APIs. I do not plan on implementing similar magic as Spring does. It is up to you to do the replacements yourself. 

I do not want to get keep parity with the Spring Framework as that would be too much and things are constantly changing. Plus, I wouldn't know all the use cases that users expect and what Spring covers.

You will notice this philosophy when retrieving application configurations from this library. `GetConfiguration` essentially returns a slice of `PropertySource`. The keys in the `Source` are Properties format. But I make no effort to unmarhsal these into a structure. I might one day add a function that can unmarshal the properties into a struct.

**Comment by pradeepkusingh** [comment]
Thanks, I am good.
